---
- name: install nginx package
  hosts: server1
  become: true
  tasks:
  - name: install nginx now
    apt: name=nginx state=present update_cache=yes
    tags: ['installnginx']

  - name: install apache
    apt: name=apache2 state=present update_cache=yes

  - name: now check the status
    service: name=nginx state=started enabled=yes
    tags: [ 'nginxpackage' ]
