---
- hosts: server1
  become: true

  tasks:
  - name: store data in a variable
    shell: cat /home/ubuntu/ansible/demo
    register: demo_index

  - name: execute shell command
    shell: echo "world"
    when: demo_index.stdout.find('hi')!=-1

  - name: execute shell
    shell: echo "nothing"
    when: "'Bhi' not in item"
    with_items: "{{demo_index}}"
    
